# Generated by Django 5.2.13 on 2026-04-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseDepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Warehouse', max_length=200)),
                ('address', models.TextField(blank=True)),
                ('lat', models.FloatField(default=52.3676)),
                ('lng', models.FloatField(default=4.9041)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
