# Generated by Django 5.2.13 on 2026-04-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_driver_on_duty_delivery_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
