# Generated by Django 5.2.13 on 2026-04-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_delivery_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='delivery',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
